// Code generated by "stringer -type=Code -linecomment -output errcode_string.go"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SystemError - -1]
	_ = x[OK-200]
	_ = x[NoContent-204]
	_ = x[BadRequest-400]
	_ = x[Authorization-401]
	_ = x[NotFound-404]
	_ = x[TokenIsNotAvailable-1000]
	_ = x[DataNotFound-4004]
	_ = x[ParamRequired-4001]
	_ = x[LogicalException-4002]
	_ = x[AccountFrozen-4003]
	_ = x[DbQueryError-1101]
	_ = x[DbInsertError-1102]
	_ = x[DbUpdateError-1103]
	_ = x[DbDeleteError-1104]
	_ = x[PhoneNumHasBeenRegistered-1301]
	_ = x[PasswordPatternError-1302]
}

const (
	_Code_name_0 = "SystemError 系统错误"
	_Code_name_1 = "OK"
	_Code_name_2 = "NoContent 内容为空"
	_Code_name_3 = "BadRequest 请求错误Authorization 访问被拒绝"
	_Code_name_4 = "NotFound 资源不存在"
	_Code_name_5 = "TokenIsNotAvailable 服务令牌不可用"
	_Code_name_6 = "DbQueryError 查询错误DbInsertError 创建错误DbUpdateError 更新错误DbDeleteError 删除错误"
	_Code_name_7 = "PhoneNumHasBeenRegistered 手机号已经被注册PasswordPatternError 密码格式不正确"
	_Code_name_8 = "ParamRequired 缺少必填参数LogicalException 逻辑异常AccountFrozen 账户被冻结DataNotFound 数据不存在"
)

var (
	_Code_index_3 = [...]uint8{0, 23, 52}
	_Code_index_6 = [...]uint8{0, 25, 51, 77, 103}
	_Code_index_7 = [...]uint8{0, 50, 92}
	_Code_index_8 = [...]uint8{0, 32, 61, 90, 118}
)

func (i Code) String() string {
	switch {
	case i == -1:
		return _Code_name_0
	case i == 200:
		return _Code_name_1
	case i == 204:
		return _Code_name_2
	case 400 <= i && i <= 401:
		i -= 400
		return _Code_name_3[_Code_index_3[i]:_Code_index_3[i+1]]
	case i == 404:
		return _Code_name_4
	case i == 1000:
		return _Code_name_5
	case 1101 <= i && i <= 1104:
		i -= 1101
		return _Code_name_6[_Code_index_6[i]:_Code_index_6[i+1]]
	case 1301 <= i && i <= 1302:
		i -= 1301
		return _Code_name_7[_Code_index_7[i]:_Code_index_7[i+1]]
	case 4001 <= i && i <= 4004:
		i -= 4001
		return _Code_name_8[_Code_index_8[i]:_Code_index_8[i+1]]
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
